jasypt:
  encryptor:
    password: "bagend"
spring:
  datasource:
    username: "semi_orauser1"
    password: "seven"
    driver-class-name: oracle.jdbc.OracleDriver
    url: "jdbc:oracle:thin:@localhost:5151:xe"
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
